lang_code = (
    # ("Kazakh", "kk"),
    # ("Uyghur", "ug"),
    # ("Ukrainian", "uk"),
    # ("Irish", "ga"),
    # ("Galician-TreeGal", "gl_treegal"),
    # ("French-ParTUT", "fr_partut"),
    # ("Latin", "la"),
    # ("Slovenian-SST", "sl_sst"),
    ("Czech-CLTT", "cs_cltt"),
    ("Hungarian", "hu"),
    ("Vietnamese", "vi"),
    ("Estonian", "et"),
    ("English-ParTUT", "en_partut"),
    ("Italian-ParTUT", "it_partut"),
    ("Latvian", "lv"),
    ("Gothic", "got"),
    ("Old_Church_Slavonic", "cu"),
    ("Turkish", "tr"),
    ("Greek", "el"),
    ("Swedish-LinES", "sv_lines"),
    ("English-LinES", "en_lines"),
    ("French-Sequoia", "fr_sequoia"),
    ("Korean", "ko"),
    ("Polish", "pl"),
    ("Swedish", "sv"),
    ("Basque", "eu"),
    ("Russian", "ru"),
    ("Galician", "gl"),
    ("Danish", "da"),
    ("Slovak", "sk"),
    ("Dutch-LassySmall", "nl_lassysmall"),
    ("Indonesian", "id"),
    ("Chinese", "zh"),
    ("Urdu", "ur"),
    ("Slovenian", "sl"),
    ("Persian", "fa"),
    ("Bulgarian", "bg"),
    ("Finnish-FTB", "fi_ftb"),
    ("Hebrew", "he"),
    ("Latin-PROIEL", "la_proiel"),
    ("Ancient_Greek", "grc"),
    ("Japanese", "ja"),
    ("Finnish", "fi"),
    ("Croatian", "hr"),
    ("Ancient_Greek-PROIEL", "grc_proiel"),
    ("Romanian", "ro"),
    ("Dutch", "nl"),
    ("English", "en"),
    ("Portuguese", "pt"),
    ("Arabic", "ar"),
    ("Norwegian-Bokmaal", "no_bokmaal"),
    ("Norwegian-Nynorsk", "no_nynorsk"),
    ("Portuguese-BR", "pt_br"),
    ("German", "de"),
    ("Latin-ITTB", "la_ittb"),
    ("Italian", "it"),
    ("Hindi", "hi"),
    ("French", "fr"),
    ("Spanish", "es"),
    ("Catalan", "ca"),
    ("Spanish-AnCora", "es_ancora"),
    ("Czech-CAC", "cs_cac"),
    ("Russian-SynTagRus", "ru_syntagrus"),
    ("Czech", "cs"),
)
