ud_path = "/data/ud-treebanks-conll2017/"
data_path = "/data/udpipe-ud-2.0-conll17-170315-supplementary-data/" \
            "ud-2.0-baselinemodel-train-embeddings/"

treebanks = {
    # only train
    'kk': "Kazakh",
    'ug': "Uyghur",
    'uk': "Ukrainian",
    'ga': "Irish",
    'gl_treegal': "Galician-TreeGal",
    'fr_partut': "French-ParTUT",
    'la': "Latin",
    'sl_sst': "Slovenian-SST",
    # with dev
    'cs_cltt': "Czech-CLTT",
    'hu': "Hungarian",
    'vi': "Vietnamese",
    'et': "Estonian",
    'en_partut': "English-ParTUT",
    'it_partut': "Italian-ParTUT",
    'lv': "Latvian",
    'got': "Gothic",
    'cu': "Old_Church_Slavonic",
    'tr': "Turkish",
    'el': "Greek",
    'sv_lines': "Swedish-LinES",
    'en_lines': "English-LinES",
    'fr_sequoia': "French-Sequoia",
    'ko': "Korean",
    'pl': "Polish",
    'sv': "Swedish",
    'eu': "Basque",
    'ru': "Russian",
    'gl': "Galician",
    'da': "Danish",
    'sk': "Slovak",
    'nl_lassysmall': "Dutch-LassySmall",
    'id': "Indonesian",
    'zh': "Chinese",
    'ur': "Urdu",
    'sl': "Slovenian",
    'fa': "Persian",
    'bg': "Bulgarian",
    'fi_ftb': "Finnish-FTB",
    'he': "Hebrew",
    'la_proiel': "Latin-PROIEL",
    'grc': "Ancient_Greek",
    'ja': "Japanese",
    'fi': "Finnish",
    'hr': "Croatian",
    'grc_proiel': "Ancient_Greek-PROIEL",
    'ro': "Romanian",
    'nl': "Dutch",
    'en': "English",
    'pt': "Portuguese",
    'ar': "Arabic",
    'no_bokmaal': "Norwegian-Bokmaal",
    'no_nynorsk': "Norwegian-Nynorsk",
    'pt_br': "Portuguese-BR",
    'de': "German",
    'la_ittb': "Latin-ITTB",
    'it': "Italian",
    'hi': "Hindi",
    'fr': "French",
    'es': "Spanish",
    'ca': "Catalan",
    'es_ancora': "Spanish-AnCora",
    'cs_cac': "Czech-CAC",
    'ru_syntagrus': "Russian-SynTagRus",
    'cs': "Czech",
}
